import { fileURLToPath } from "node:url";
import { defineConfig } from "oxlint";

const error = "error";

/** @type {import("oxlint").OxlintConfig["plugins"]} */
const plugins = [
  "eslint",
  "import",
  "jsx-a11y",
  "oxc",
  "promise",
  "react",
  "typescript",
  "unicorn",
  "vitest",
];

export const jsPlugin = fileURLToPath(new URL("./plugin.js", import.meta.url));

// Oxlint default-on rules are pinned explicitly so Hodor keeps the same baseline if future Oxlint versions change defaults.
const defaultOxlintRuleEntries = [
  ["no-implied-eval", error],
  ["constructor-super", error],
  ["for-direction", error],
  ["getter-return", error],
  ["no-async-promise-executor", error],
  ["no-caller", error],
  ["no-class-assign", error],
  ["no-compare-neg-zero", error],
  ["no-cond-assign", error],
  ["no-const-assign", error],
  ["no-constant-binary-expression", error],
  ["no-constant-condition", error],
  ["no-control-regex", error],
  ["no-debugger", error],
  ["no-delete-var", error],
  ["no-dupe-class-members", error],
  ["no-dupe-else-if", error],
  ["no-dupe-keys", error],
  ["no-duplicate-case", error],
  ["no-empty-character-class", error],
  ["no-empty-pattern", error],
  ["no-empty-static-block", error],
  ["no-eval", error],
  ["no-ex-assign", error],
  ["no-extra-boolean-cast", error],
  ["no-func-assign", error],
  ["no-global-assign", error],
  ["no-import-assign", error],
  ["no-invalid-regexp", error],
  ["no-irregular-whitespace", error],
  ["no-iterator", error],
  ["no-loss-of-precision", error],
  ["no-misleading-character-class", error],
  ["no-new-native-nonconstructor", error],
  ["no-nonoctal-decimal-escape", error],
  ["no-obj-calls", error],
  ["no-self-assign", error],
  ["no-setter-return", error],
  ["no-shadow-restricted-names", error],
  ["no-sparse-arrays", error],
  ["no-this-before-super", error],
  ["no-unassigned-vars", error],
  ["no-unreachable", error],
  ["no-unsafe-finally", error],
  ["no-unsafe-negation", error],
  ["no-unsafe-optional-chaining", error],
  ["no-unused-expressions", error],
  ["no-unused-labels", error],
  ["no-unused-private-class-members", error],
  ["no-unused-vars", error],
  ["no-useless-backreference", error],
  ["no-useless-catch", error],
  ["no-useless-escape", error],
  ["no-useless-rename", error],
  ["no-with", error],
  ["require-yield", error],
  ["use-isnan", error],
  ["valid-typeof", error],
  ["oxc/bad-array-method-on-arguments", error],
  ["oxc/bad-char-at-comparison", error],
  ["oxc/bad-comparison-sequence", error],
  ["oxc/bad-min-max-func", error],
  ["oxc/bad-object-literal-comparison", error],
  ["oxc/bad-replace-all-arg", error],
  ["oxc/const-comparisons", error],
  ["oxc/double-comparisons", error],
  ["oxc/erasing-op", error],
  ["oxc/missing-throw", error],
  ["oxc/number-arg-out-of-range", error],
  ["oxc/only-used-in-recursion", error],
  ["oxc/uninvoked-array-callback", error],
  ["typescript/prefer-string-starts-ends-with", error],
  ["typescript/await-thenable", error],
  ["typescript/no-array-delete", error],
  ["typescript/no-base-to-string", error],
  ["typescript/no-duplicate-enum-values", error],
  ["typescript/no-duplicate-type-constituents", error],
  ["typescript/no-extra-non-null-assertion", error],
  ["typescript/no-floating-promises", error],
  ["typescript/no-for-in-array", error],
  ["typescript/no-implied-eval", error],
  ["typescript/no-meaningless-void-operator", error],
  ["typescript/no-misused-new", error],
  ["typescript/no-misused-spread", error],
  ["typescript/no-non-null-asserted-optional-chain", error],
  ["typescript/no-redundant-type-constituents", error],
  ["typescript/no-this-alias", error],
  ["typescript/no-unnecessary-parameter-property-assignment", error],
  ["typescript/no-unsafe-declaration-merging", error],
  ["typescript/no-unsafe-unary-minus", error],
  ["typescript/no-useless-default-assignment", error],
  ["typescript/no-useless-empty-export", error],
  ["typescript/no-wrapper-object-types", error],
  ["typescript/prefer-as-const", error],
  ["typescript/prefer-namespace-keyword", error],
  ["typescript/require-array-sort-compare", error],
  ["typescript/restrict-template-expressions", error],
  ["typescript/triple-slash-reference", error],
  ["typescript/unbound-method", error],
  ["unicorn/no-await-in-promise-methods", error],
  ["unicorn/no-empty-file", error],
  ["unicorn/no-invalid-fetch-options", error],
  ["unicorn/no-invalid-remove-event-listener", error],
  ["unicorn/no-new-array", error],
  ["unicorn/no-single-promise-in-promise-methods", error],
  ["unicorn/no-thenable", error],
  ["unicorn/no-unnecessary-await", error],
  ["unicorn/no-useless-fallback-in-spread", error],
  ["unicorn/no-useless-length-check", error],
  ["unicorn/no-useless-spread", error],
  ["unicorn/prefer-set-size", error],
  ["unicorn/prefer-string-starts-ends-with", error],
];

const coreRuleEntries = [
  ["accessor-pairs", error],
  ["array-callback-return", error],
  ["eqeqeq", error],
  ["no-alert", error],
  ["no-array-constructor", error],
  ["no-case-declarations", error],
  ["no-constructor-return", error],
  ["no-empty-function", error],
  ["no-eq-null", error],
  ["no-extra-bind", error],
  ["no-fallthrough", error],
  ["no-loop-func", error],
  ["no-new", error],
  ["no-new-wrappers", error],
  ["no-object-constructor", error],
  ["no-param-reassign", error],
  ["no-promise-executor-return", error],
  ["no-prototype-builtins", error],
  ["no-regex-spaces", error],
  ["no-self-compare", error],
  ["no-sequences", error],
  ["no-shadow", error],
  ["no-throw-literal", error],
  ["no-unmodified-loop-condition", error],
  ["no-unneeded-ternary", error],
  ["no-use-before-define", error],
  ["no-useless-concat", error],
  ["no-useless-constructor", error],
  ["no-useless-return", error],
  ["no-var", error],
  ["prefer-const", error],
  ["prefer-object-has-own", error],
  ["prefer-object-spread", error],
  ["prefer-promise-reject-errors", error],
  ["prefer-regex-literals", error],
  ["prefer-rest-params", error],
  ["prefer-spread", error],
  ["prefer-template", error],
  ["radix", error],
  ["require-await", error],
  ["func-style", [error, "declaration"]],
];

const importRuleEntries = [
  ["import/consistent-type-specifier-style", error],
  ["import/no-cycle", error],
  ["import/no-default-export", error],
  ["import/no-duplicates", error],
  ["import/no-empty-named-blocks", error],
  ["import/no-mutable-exports", error],
  ["import/no-named-as-default", error],
  ["import/no-named-as-default-member", error],
  ["import/no-self-import", error],
];

const oxcRuleEntries = [
  ["oxc/approx-constant", error],
  ["oxc/branches-sharing-code", error],
  ["oxc/misrefactored-assign-op", error],
  ["oxc/no-accumulating-spread", error],
  ["oxc/no-barrel-file", error],
  ["oxc/no-const-enum", error],
  ["oxc/no-map-spread", error],
  ["oxc/no-this-in-exported-function", error],
];

const promiseRuleEntries = [
  ["promise/always-return", error],
  ["promise/no-multiple-resolved", error],
  ["promise/no-nesting", error],
  ["promise/no-return-wrap", error],
  ["promise/param-names", error],
  ["promise/prefer-await-to-callbacks", error],
  ["promise/prefer-await-to-then", error],
];

const typescriptRuleEntries = [
  [
    "typescript/consistent-type-assertions",
    [
      error,
      {
        assertionStyle: "as",
        objectLiteralTypeAssertions: "never",
      },
    ],
  ],
  ["typescript/consistent-type-definitions", [error, "type"]],
  ["typescript/consistent-type-exports", error],
  ["typescript/consistent-type-imports", error],
  ["typescript/no-deprecated", error],
  ["typescript/no-empty-object-type", error],
  ["typescript/no-explicit-any", error],
  ["typescript/no-misused-promises", error],
  ["typescript/no-non-null-asserted-nullish-coalescing", error],
  ["typescript/no-unnecessary-condition", error],
  ["typescript/no-unnecessary-type-arguments", error],
  ["typescript/no-unnecessary-type-assertion", error],
  ["typescript/no-unnecessary-type-conversion", error],
  ["typescript/no-unnecessary-type-parameters", error],
  ["typescript/no-unsafe-argument", error],
  ["typescript/no-unsafe-assignment", error],
  ["typescript/no-unsafe-call", error],
  ["typescript/no-unsafe-enum-comparison", error],
  ["typescript/no-unsafe-member-access", error],
  ["typescript/no-unsafe-return", error],
  ["typescript/no-unsafe-type-assertion", error],
  ["typescript/only-throw-error", error],
  ["typescript/prefer-find", error],
  ["typescript/prefer-for-of", error],
  ["typescript/prefer-function-type", error],
  ["typescript/prefer-nullish-coalescing", error],
  ["typescript/prefer-optional-chain", error],
  ["typescript/prefer-readonly", error],
  ["typescript/prefer-reduce-type-parameter", error],
  ["typescript/prefer-regexp-exec", error],
  ["typescript/promise-function-async", error],
  ["typescript/restrict-plus-operands", error],
  ["typescript/return-await", error],
  ["typescript/strict-boolean-expressions", error],
  ["typescript/switch-exhaustiveness-check", error],
];

const reactRuleEntries = [
  ["react/button-has-type", error],
  ["react/checked-requires-onchange-or-readonly", error],
  ["react/exhaustive-deps", error],
  ["react/iframe-missing-sandbox", error],
  ["react/jsx-boolean-value", error],
  ["react/jsx-curly-brace-presence", error],
  ["react/jsx-handler-names", error],
  ["react/jsx-key", error],
  ["react/jsx-no-constructed-context-values", error],
  ["react/jsx-no-duplicate-props", error],
  ["react/jsx-no-target-blank", error],
  ["react/jsx-no-useless-fragment", error],
  ["react/jsx-pascal-case", error],
  ["react/jsx-props-no-spread-multi", error],
  ["react/jsx-props-no-spreading", error],
  ["react/no-array-index-key", error],
  ["react/no-children-prop", error],
  ["react/no-danger", error],
  ["react/no-danger-with-children", error],
  ["react/no-object-type-as-default-prop", error],
  ["react/no-unknown-property", error],
  ["react/no-unstable-nested-components", error],
  ["react/only-export-components", error],
  ["react/rules-of-hooks", error],
  ["react/self-closing-comp", error],
];

const jsxA11yRuleEntries = [
  ["jsx_a11y/alt-text", error],
  ["jsx_a11y/anchor-has-content", error],
  ["jsx_a11y/anchor-is-valid", error],
  ["jsx_a11y/aria-activedescendant-has-tabindex", error],
  ["jsx_a11y/aria-props", error],
  ["jsx_a11y/aria-proptypes", error],
  ["jsx_a11y/aria-role", error],
  ["jsx_a11y/aria-unsupported-elements", error],
  ["jsx_a11y/autocomplete-valid", error],
  ["jsx_a11y/click-events-have-key-events", error],
  ["jsx_a11y/control-has-associated-label", error],
  ["jsx_a11y/heading-has-content", error],
  ["jsx_a11y/html-has-lang", error],
  ["jsx_a11y/iframe-has-title", error],
  ["jsx_a11y/img-redundant-alt", error],
  ["jsx_a11y/interactive-supports-focus", error],
  ["jsx_a11y/label-has-associated-control", error],
  ["jsx_a11y/lang", error],
  ["jsx_a11y/media-has-caption", error],
  ["jsx_a11y/mouse-events-have-key-events", error],
  ["jsx_a11y/no-access-key", error],
  ["jsx_a11y/no-aria-hidden-on-focusable", error],
  ["jsx_a11y/no-autofocus", error],
  ["jsx_a11y/no-distracting-elements", error],
  ["jsx_a11y/no-interactive-element-to-noninteractive-role", error],
  ["jsx_a11y/no-noninteractive-element-interactions", error],
  ["jsx_a11y/no-noninteractive-element-to-interactive-role", error],
  ["jsx_a11y/no-noninteractive-tabindex", error],
  ["jsx_a11y/no-redundant-roles", error],
  ["jsx_a11y/no-static-element-interactions", error],
  ["jsx_a11y/prefer-tag-over-role", error],
  ["jsx_a11y/role-has-required-aria-props", error],
  ["jsx_a11y/role-supports-aria-props", error],
  ["jsx_a11y/scope", error],
  ["jsx_a11y/tabindex-no-positive", error],
];

const vitestRuleEntries = [
  ["vitest/expect-expect", error],
  ["vitest/no-commented-out-tests", error],
  ["vitest/no-conditional-expect", error],
  ["vitest/no-conditional-tests", error],
  ["vitest/no-disabled-tests", error],
  ["vitest/no-focused-tests", error],
  ["vitest/no-identical-title", error],
  ["vitest/no-standalone-expect", error],
  ["vitest/prefer-comparison-matcher", error],
  ["vitest/prefer-equality-matcher", error],
  ["vitest/prefer-expect-resolves", error],
  ["vitest/prefer-expect-type-of", error],
  ["vitest/prefer-strict-equal", error],
  ["vitest/prefer-to-be", error],
  ["vitest/prefer-to-contain", error],
  ["vitest/prefer-to-have-been-called-times", error],
  ["vitest/prefer-to-have-length", error],
  ["vitest/require-to-throw-message", error],
  ["vitest/valid-describe-callback", error],
  ["vitest/valid-expect", error],
  ["vitest/valid-expect-in-promise", error],
  ["vitest/valid-title", error],
];

const unicornRuleEntries = [
  ["unicorn/consistent-function-scoping", error],
  ["unicorn/error-message", error],
  ["unicorn/explicit-length-check", error],
  ["unicorn/new-for-builtins", error],
  ["unicorn/no-array-callback-reference", error],
  ["unicorn/no-array-for-each", error],
  ["unicorn/no-array-reduce", error],
  ["unicorn/no-array-reverse", error],
  ["unicorn/no-array-sort", error],
  ["unicorn/no-instanceof-array", error],
  ["unicorn/no-lonely-if", error],
  ["unicorn/no-negated-condition", error],
  ["unicorn/no-new-buffer", error],
  ["unicorn/no-unreadable-array-destructuring", error],
  ["unicorn/no-useless-promise-resolve-reject", error],
  ["unicorn/no-useless-undefined", error],
  ["unicorn/prefer-add-event-listener", error],
  ["unicorn/prefer-array-find", error],
  ["unicorn/prefer-array-flat", error],
  ["unicorn/prefer-array-flat-map", error],
  ["unicorn/prefer-array-index-of", error],
  ["unicorn/prefer-array-some", error],
  ["unicorn/prefer-at", error],
  ["unicorn/prefer-date-now", error],
  ["unicorn/prefer-includes", error],
  ["unicorn/prefer-math-min-max", error],
  ["unicorn/prefer-math-trunc", error],
  ["unicorn/prefer-modern-dom-apis", error],
  ["unicorn/prefer-native-coercion-functions", error],
  ["unicorn/prefer-negative-index", error],
  ["unicorn/prefer-number-properties", error],
  ["unicorn/prefer-object-from-entries", error],
  ["unicorn/prefer-optional-catch-binding", error],
  ["unicorn/prefer-prototype-methods", error],
  ["unicorn/prefer-query-selector", error],
  ["unicorn/prefer-regexp-test", error],
  ["unicorn/prefer-set-has", error],
  ["unicorn/prefer-set-size", error],
  ["unicorn/prefer-string-replace-all", error],
  ["unicorn/prefer-string-slice", error],
  ["unicorn/prefer-string-starts-ends-with", error],
  ["unicorn/prefer-structured-clone", error],
  ["unicorn/throw-new-error", error],
];

const customRuleEntries = [
  ["hodor/no-positional-func-args", error],
  ["hodor/no-json-parse-type-assertion", error],
  ["hodor/no-react-fc", error],
  ["hodor/no-forward-ref", error],
  ["hodor/no-default-react-memoization", error],
  ["hodor/no-function-deps-in-effect", error],
];

export const customRules = Object.fromEntries(customRuleEntries);

const basicRuleEntries = [
  ...defaultOxlintRuleEntries,
  ...coreRuleEntries,
  ...importRuleEntries,
  ...oxcRuleEntries,
  ...promiseRuleEntries,
  ...unicornRuleEntries,
];

const ruleGroups = {
  defaults: Object.fromEntries(defaultOxlintRuleEntries),
  basic: Object.fromEntries(basicRuleEntries),
  core: Object.fromEntries(coreRuleEntries),
  import: Object.fromEntries(importRuleEntries),
  oxc: Object.fromEntries(oxcRuleEntries),
  promise: Object.fromEntries(promiseRuleEntries),
  unicorn: Object.fromEntries(unicornRuleEntries),
  react: Object.fromEntries(reactRuleEntries),
  jsxA11y: Object.fromEntries(jsxA11yRuleEntries),
  typescript: Object.fromEntries(typescriptRuleEntries),
  vitest: Object.fromEntries(vitestRuleEntries),
  hodor: customRules,
  all: Object.fromEntries([
    ...basicRuleEntries,
    ...reactRuleEntries,
    ...jsxA11yRuleEntries,
    ...typescriptRuleEntries,
    ...vitestRuleEntries,
    ...customRuleEntries,
  ]),
};

export const config = defineConfig({
  plugins,
  rules: ruleGroups.all,
  overrides: [
    {
      files: ["oxlint.config.*"],
      rules: {
        "import/no-default-export": "off",
        "import/no-named-as-default-member": "off",
      },
    },
  ],
});
